export const API_URL = {
  USERS: "/user",
  GETALLUSER: "/user/get-user",
  LOGIN: "/auth/login",
  PROJECT: "/project",
  LANGUAGE: "/language",
  TECHNICAL: "/technical",
  TECHNICALPAGI: "/technical/pagination",
  LANGUAGEPAGI: "/language/pagination",
  POSITIONPAGI: "/position/pagination",
  CREATE_USER: "/user",
  TECHNOLOGY: "/technical",
  POSITION: "/position",
  PROJECTS: "/project",
  EXPORTCV: "/file/generate-cv",
  GETDETAILPROJECT: "/project/${id}",
  CREATE_PROJECT: "/project",
  ADD_EMPLOYEE: "/project/add-employee",
  UNASSIGN_EMPLOYEE: "/project/unassign-employee",
  FILE: "/file",
  LANGUAGE_MEMBER: "/languageMember",
  TECHNICAL_MEMBER: "/technicalMember",
};
