export const API_URL = {
  USERS: "/user",
  GETALLUSER: "/user/get-user",
  LOGIN: "/auth/login",
  PROJECT: "/project",
  LANGUAGE: "/language",
  TECHNICAL: "/technical",
  CREATE_USER: "/user",
  TECHNOLOGY: "/technical",
  POSITION: "/position",
  PROJECTS: "/project",
  GETDETAILPROJECT: "/project/${id}",
  CREATE_PROJECT: "/project",
  ADD_EMPLOYEE: "/project/add-employee",
  UNASSIGN_EMPLOYEE: "/project/unassign-employee/${id}",
};
