export const QUERY_KEY = {
  USERS: "USERS",
  USERS_NO_PAGINATE: "USERS_NO_PAGINATE",
  TECHNICALS: "TECHNICALS",
  TECHNICAL: "TECHNICAL",
  CREATETECHNICAL: "CREATETECHNICAL",
  UPDATETECHNICAL: "UPDATETECHNICAL",
  LANGGUAGES: "LANGGUAGES",
  TECH: "TECH",
  LANG: "LANG",
  POSITION: "POSITION",
  PROJECTS: "PROJECTS",
  PROJECT: "PROJECT",
};
